"""Константы приложения."""

DEFAULT_POLL_INTERVAL = 600
DEFAULT_BOT_POLL_INTERVAL = 60
DEFAULT_REQUEST_TIMEOUT = 30
DEFAULT_PAGE_SIZE = 100
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_RECENT_LIMIT = 10
PAGE_SIZE = 10
SEARCH_LIMIT = 50
NOTIFY_LIMIT = 50
MAX_BUFFER_SIZE = 1000
MAX_RETRY_DELAY = 60
RETRY_BACKOFF_START = 1

WHAPI_CHATS_ENDPOINT = "/chats"
WHAPI_MESSAGES_ENDPOINT = "/messages/list/{chat_id}"
WHAPI_SKIPPED_CHAT_IDS = {"status@broadcast", "0@s.whatsapp.net"}

HEALTH_PATH = "/health"
DEFAULT_WORKER_HEALTH_PORT = 8081
DEFAULT_BOT_HEALTH_PORT = 8082

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
