"""Пользовательские сообщения бота и значения по умолчанию для команд."""

START_MESSAGE = (
    "Привет! Я слежу за сообщениями в WhatsApp и Max и присылаю совпадения по вашим ключевым словам.\n\n"
    "Быстрый старт:\n"
    "- Добавить ключевое слово: /add_keyword кофе\n"
    "- Удалить ключевое слово: /remove_keyword кофе\n"
    "- Список ключевых слов: /list_keywords\n"
    "- Поиск по ключевым словам: /search\n"
    "- Последние сообщения: /recent 10\n\n"
    "Для удобства доступно меню с кнопками ниже."
)

MENU_MESSAGE = (
    "Выберите действие в меню ниже или используйте команды:\n"
    "/add_keyword слово\n"
    "/remove_keyword слово\n"
    "/list_keywords\n"
    "/search\n"
    "/recent 10"
)

RECENT_USAGE = "Использование: /recent 10"
ADD_KEYWORD_USAGE = "Использование: /add_keyword слово\nПример: /add_keyword доставка"
REMOVE_KEYWORD_USAGE = "Использование: /remove_keyword слово\nПример: /remove_keyword доставка"
NO_KEYWORDS_MESSAGE = "Ключевых слов пока нет. Добавьте их командой /add_keyword слово."
NO_RESULTS_MESSAGE = "Ничего не найдено. Попробуйте другие ключевые слова."
DB_ERROR_MESSAGE = "База данных временно недоступна. Попробуйте позже."
KEYWORD_ADDED_MESSAGE = "Готово! Ключевое слово добавлено: {keyword}"
KEYWORD_EXISTS_MESSAGE = "Такое ключевое слово уже есть: {keyword}"
KEYWORD_REMOVED_MESSAGE = "Удалено ключевое слово: {keyword}"
KEYWORD_NOT_FOUND_MESSAGE = "Не нашел такого ключевого слова: {keyword}"
KEYWORDS_LIST_HEADER = "Ваши ключевые слова ({count}):"
KEYWORDS_LIST_ITEM_TEMPLATE = "{index}. {keyword}"
RECENT_RESULTS_HEADER = "Последние сообщения ({count}):"
SEARCH_RESULTS_HEADER = "Найдено сообщений: {count}"

MENU_PLACEHOLDER = "Введите команду или выберите пункт"
MENU_BUTTON_RECENT = "/recent"
MENU_BUTTON_SEARCH = "/search"
MENU_BUTTON_LIST = "/list_keywords"
MENU_BUTTON_ADD = "/add_keyword"
MENU_BUTTON_REMOVE = "/remove_keyword"
MENU_BUTTON_HELP = "/menu"

COMMAND_START_DESCRIPTION = "О боте и быстрый старт"
COMMAND_MENU_DESCRIPTION = "Показать меню"
COMMAND_HELP_DESCRIPTION = "Справка"
COMMAND_ADD_DESCRIPTION = "Добавить ключевое слово"
COMMAND_REMOVE_DESCRIPTION = "Удалить ключевое слово"
COMMAND_LIST_DESCRIPTION = "Список ключевых слов"
COMMAND_SEARCH_DESCRIPTION = "Поиск сообщений по ключевым словам"
COMMAND_RECENT_DESCRIPTION = "Последние сообщения"

HEADER_CHAT_LABEL = "Чат"
HEADER_SENDER_LABEL = "Отправитель"
HEADER_TIME_LABEL = "Время"
HEADER_TYPE_LABEL = "Тип"
HEADER_LINKS_LABEL = "Ссылки"
MESSAGE_SEPARATOR = "-----"
